# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180821_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('authormanage', 'Может создавать, модернизировать, удалять записи об авторах'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('bookmanage', 'Может создавать, модернизировать, удалять записи о книгах'),)},
        ),
    ]
